In [13]:
import matplotlib.pyplot as plt
import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


In [2]:
X, y = load_iris(return_X_y=True)

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [4]:
# Classificador 1 
from sklearn.naive_bayes import GaussianNB

c1 = GaussianNB()
c1.fit(X_train, y_train)

c1_y_pred_prob = c1.predict_proba(X_test[0, None])
print(c1_y_pred_prob)

[[1.34178204e-94 9.95499546e-01 4.50045385e-03]]


In [5]:
# Classificador 2
from sklearn.naive_bayes import MultinomialNB

c2 = MultinomialNB()
c2.fit(X_train, y_train)

c2_y_pred_prob = c2.predict_proba(X_test[0, None])
print(c2_y_pred_prob)


[[0.04563945 0.50691224 0.44744831]]


In [6]:
# Classificador 3
from sklearn.neural_network import MLPClassifier

c3 = MLPClassifier(alpha=1, max_iter=1000)
c3.fit(X_train, y_train)

c3_y_pred_prob = c3.predict_proba(X_test[0, None])
print(c3_y_pred_prob)


[[0.00389287 0.90444014 0.09166699]]


In [7]:
#Classes 
classes = load_iris().target_names

count = 0 
sum = 0

output_classes = []
output_sum = []
output_prod = []

#Classes e propabilidades
for var in classes:
  print('\nLabel: ', var)
  print('\t Probabilidade: ', c1_y_pred_prob[0, count])
  print('\t Probabilidade: ', c2_y_pred_prob[0, count])
  print('\t Probabilidade: ', c3_y_pred_prob[0, count])

  sum = c1_y_pred_prob[0, count] + c2_y_pred_prob[0, count] + c3_y_pred_prob[0, count]
  output_sum.append(sum)

  prod = c1_y_pred_prob[0, count] * c2_y_pred_prob[0, count] * c3_y_pred_prob[0, count]
  output_prod.append(prod)

  output_classes.append(var)
  print('Sum: ', sum)
  print('Prod:', prod)
  count += 1



Label:  setosa
	 Probabilidade:  1.3417820354186536e-94
	 Probabilidade:  0.045639445818471194
	 Probabilidade:  0.0038928660585093827
Sum:  0.049532311876980574
Prod: 2.3839206551839084e-98

Label:  versicolor
	 Probabilidade:  0.9954995461546398
	 Probabilidade:  0.5069122446657047
	 Probabilidade:  0.9044401439028597
Sum:  2.4068519347232042
Prod: 0.4564084524104777

Label:  virginica
	 Probabilidade:  0.004500453845360351
	 Probabilidade:  0.44744830951582515
	 Probabilidade:  0.09166699003863092
Sum:  0.5436157533998164
Prod: 0.00018459169382045327


In [8]:
#Predição Final

#1. Obter a classe de maior valor
max_value = max(output_sum)
max_value_prod = max(output_prod)

#2. Obter a classe 
max_index = output_sum.index(max_value)
max_prod_index = output_prod.index(max_value_prod)

label_final = output_classes[max_index] 
label_final_prod = output_classes[max_prod_index] 

print('Classe final - Regra da Soma: ', label_final, '- valor:', max_value )
print('Classe final - Regra do Produto: ', label_final_prod,  '- valor:', max_value_prod)

Classe final - Regra da Soma:  versicolor - valor: 2.4068519347232042
Classe final - Regra do Produto:  versicolor - valor: 0.4564084524104777
